"""add auth identities

Revision ID: 0bbff1bf2036
Revises: a1a8de9c3216
Create Date: 2026-09-27 19:58:07.031304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bbff1bf2036'
down_revision = 'a1a8de9c3216'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_identities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_user_id', sa.String(length=255), nullable=False),
    sa.Column('provider_email', sa.String(length=255), nullable=True),
    sa.Column('selected', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_user_id', name='uq_auth_identity_provider_user')
    )
    
    op.create_index(
        'uq_auth_identity_selected_user',
        'auth_identities',
        ['user_id'],
        unique=True,
        postgresql_where=sa.text('selected=true')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        'uq_auth_identity_selected_user',
        table_name='auth_identities'
    )
    
    op.drop_table('auth_identities')
    # ### end Alembic commands ###
