"""add user profiles and registration flow

Revision ID: 846544bb6880
Revises: d65c1f1b4135
Create Date: 2026-09-19 19:23:55.923923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '846544bb6880'
down_revision = 'd65c1f1b4135'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_permissions_name'), ['name'], unique=True)

    op.create_table('registration_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('position', sa.String(length=150), nullable=True),
    sa.Column('specialty', sa.String(length=150), nullable=True),
    sa.Column('professional_card', sa.String(length=100), nullable=True),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('otp_requests_count', sa.Integer(), nullable=False),
    sa.Column('failed_otp_count', sa.Integer(), nullable=False),
    sa.Column('blocked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('otp_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('registration_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_registration_sessions_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_registration_sessions_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_registration_sessions_token_hash'), ['token_hash'], unique=True)

    op.create_table('registration_otps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registration_session_id', sa.Integer(), nullable=False),
    sa.Column('otp_hash', sa.String(length=255), nullable=False),
    sa.Column('salt', sa.String(length=255), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['registration_session_id'], ['registration_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('registration_otps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_registration_otps_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_registration_otps_registration_session_id'), ['registration_session_id'], unique=False)

    op.create_table('role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('user_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('position', sa.String(length=150), nullable=True),
    sa.Column('specialty', sa.String(length=150), nullable=True),
    sa.Column('professional_card', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_profiles_user_id'), ['user_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_profiles_user_id'))

    op.drop_table('user_profiles')
    op.drop_table('role_permissions')
    with op.batch_alter_table('registration_otps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_registration_otps_registration_session_id'))
        batch_op.drop_index(batch_op.f('ix_registration_otps_expires_at'))

    op.drop_table('registration_otps')
    with op.batch_alter_table('registration_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_registration_sessions_token_hash'))
        batch_op.drop_index(batch_op.f('ix_registration_sessions_expires_at'))
        batch_op.drop_index(batch_op.f('ix_registration_sessions_email'))

    op.drop_table('registration_sessions')
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_permissions_name'))

    op.drop_table('permissions')
    # ### end Alembic commands ###
