"""create password recovery session

Revision ID: 93efed197cc9
Revises: 8556f573eef0
Create Date: 2026-09-18 16:08:19.666071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93efed197cc9'
down_revision = '8556f573eef0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_recovery_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('password_recovery_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_password_recovery_sessions_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_password_recovery_sessions_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_password_recovery_sessions_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('password_recovery_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_password_recovery_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_password_recovery_sessions_token_hash'))
        batch_op.drop_index(batch_op.f('ix_password_recovery_sessions_expires_at'))

    op.drop_table('password_recovery_sessions')
    # ### end Alembic commands ###
