"""add identification fields

Revision ID: a1a8de9c3216
Revises: b7d4a5fa4007
Create Date: 2026-09-27 15:46:39.037038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1a8de9c3216'
down_revision = 'b7d4a5fa4007'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registration_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('identification_type', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('identification_number', sa.String(length=50), nullable=False))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('identification_type', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('identification_number', sa.String(length=50), nullable=False))
        batch_op.create_unique_constraint('uq_user_identification', ['identification_type', 'identification_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_identification', type_='unique')
        batch_op.drop_column('identification_number')
        batch_op.drop_column('identification_type')

    with op.batch_alter_table('registration_sessions', schema=None) as batch_op:
        batch_op.drop_column('identification_number')
        batch_op.drop_column('identification_type')

    # ### end Alembic commands ###
