"""add last_name to registration_sessions

Revision ID: b7d4a5fa4007
Revises: ceae4b88526f
Create Date: 2026-09-20 13:19:20.342345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7d4a5fa4007'
down_revision = 'ceae4b88526f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registration_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_name', sa.String(length=150), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registration_sessions', schema=None) as batch_op:
        batch_op.drop_column('last_name')

    # ### end Alembic commands ###
