"""add recovery session otp limits

Revision ID: d65c1f1b4135
Revises: d91e6e1a08ae
Create Date: 2026-09-19 14:42:33.796406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd65c1f1b4135'
down_revision = 'd91e6e1a08ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Agregar las nuevas columnas temporalmente como nullable
    with op.batch_alter_table(
        'password_recovery_sessions',
        schema=None
    ) as batch_op:

        batch_op.add_column(
            sa.Column(
                'otp_requests_count',
                sa.Integer(),
                nullable=True
            )
        )

        batch_op.add_column(
            sa.Column(
                'failed_otp_count',
                sa.Integer(),
                nullable=True
            )
        )

        batch_op.add_column(
            sa.Column(
                'blocked_at',
                sa.DateTime(timezone=True),
                nullable=True
            )
        )

    # 2. Inicializar los registros existentes
    op.execute("""
        UPDATE password_recovery_sessions
        SET otp_requests_count = 1
        WHERE otp_requests_count IS NULL
    """)

    op.execute("""
        UPDATE password_recovery_sessions
        SET failed_otp_count = 0
        WHERE failed_otp_count IS NULL
    """)

    # 3. Convertir las columnas obligatorias a NOT NULL
    with op.batch_alter_table(
        'password_recovery_sessions',
        schema=None
    ) as batch_op:

        batch_op.alter_column(
            'otp_requests_count',
            existing_type=sa.Integer(),
            nullable=False
        )

        batch_op.alter_column(
            'failed_otp_count',
            existing_type=sa.Integer(),
            nullable=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table(
        'password_recovery_sessions',
        schema=None
    ) as batch_op:

        batch_op.drop_column('blocked_at')
        batch_op.drop_column('failed_otp_count')
        batch_op.drop_column('otp_requests_count')

    # ### end Alembic commands ###