"""simplify password recovery

Revision ID: d91e6e1a08ae
Revises: 93efed197cc9
Create Date: 2026-09-18 20:37:50.552056

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd91e6e1a08ae'
down_revision = '93efed197cc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('password_reset_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_password_reset_sessions_expires_at'))
        batch_op.drop_index(batch_op.f('ix_password_reset_sessions_token_hash'))
        batch_op.drop_index(batch_op.f('ix_password_reset_sessions_user_id'))

    op.drop_table('password_reset_sessions')
    with op.batch_alter_table('password_recovery_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('otp_verified_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('password_recovery_sessions', schema=None) as batch_op:
        batch_op.drop_column('otp_verified_at')

    op.create_table('password_reset_sessions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('used_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('revoked_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('password_reset_sessions_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('password_reset_sessions_pkey'))
    )
    with op.batch_alter_table('password_reset_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_password_reset_sessions_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_password_reset_sessions_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_password_reset_sessions_expires_at'), ['expires_at'], unique=False)

    # ### end Alembic commands ###
